/**
 * js/data.js — Datos de prueba locales
 * E-commerce de Belleza | BeautyShop
 */

export const categorias = [
  { id: 1, nombre: "Maquillaje",       icono: "💄" },
  { id: 2, nombre: "Cuidado Facial",   icono: "🧴" },
  { id: 3, nombre: "Cuidado Corporal", icono: "🛁" },
  { id: 4, nombre: "Cabello",          icono: "💇" },
  { id: 5, nombre: "Fragancias",       icono: "🌸" },
  { id: 6, nombre: "Uñas",            icono: "💅" },
];

export const productos = [
  // --- MAQUILLAJE ---
  {
    id: 1,
    nombre: "Base de Maquillaje Mate",
    descripcion: "Base líquida de larga duración con acabado mate. Cobertura media a total, ideal para piel grasa y mixta. Con protección SPF 25.",
    precio: 45000,
    descuento: 10,
    categoriaId: 1,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.03.59 AM.jpeg",
    vendedor: "Glamour Colombia",
    vendedorId: 3,
    calificacion: 4.5,
    resenas: 128,
    stock: 50,
    etiquetas: ["maquillaje", "base", "mate", "larga duración"],
    destacado: true,
    nuevo: false,
  },
  {
    id: 2,
    nombre: "Paleta de Sombras Sunset",
    descripcion: "Paleta de 12 sombras con tonos cálidos. Incluye acabados mate, shimmer y glitter. Alta pigmentación y larga duración.",
    precio: 68000,
    descuento: 0,
    categoriaId: 1,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.03.59 AM (1).jpeg",
    vendedor: "Glamour Colombia",
    vendedorId: 3,
    calificacion: 4.8,
    resenas: 95,
    stock: 30,
    etiquetas: ["maquillaje", "sombras", "ojos", "paleta"],
    destacado: true,
    nuevo: false,
  },
  {
    id: 3,
    nombre: "Labial Hidratante Rosa Nude",
    descripcion: "Labial cremoso con vitamina E y aceite de argán. Color rosa nude perfecto para uso diario. Dura hasta 8 horas.",
    precio: 22000,
    descuento: 15,
    categoriaId: 1,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.03.59 AM (2).jpeg",
    vendedor: "BellezaNatural",
    vendedorId: 4,
    calificacion: 4.3,
    resenas: 67,
    stock: 80,
    etiquetas: ["maquillaje", "labial", "hidratante", "nude"],
    destacado: false,
    nuevo: true,
  },
  {
    id: 4,
    nombre: "Máscara de Pestañas Volumen XXL",
    descripcion: "Máscara de pestañas de fórmula enriquecida con keratina. Da volumen y alargamiento extremo. Resistente al agua.",
    precio: 35000,
    descuento: 0,
    categoriaId: 1,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.03.59 AM (3).jpeg",
    vendedor: "Glamour Colombia",
    vendedorId: 3,
    calificacion: 4.6,
    resenas: 112,
    stock: 45,
    etiquetas: ["maquillaje", "mascara", "pestañas", "waterproof"],
    destacado: false,
    nuevo: false,
  },
  // --- CUIDADO FACIAL ---
  {
    id: 5,
    nombre: "Sérum Vitamina C Antioxidante",
    descripcion: "Sérum facial con 20% de vitamina C pura. Ilumina, unifica el tono y reduce manchas. Fórmula estabilizada para mayor eficacia.",
    precio: 89000,
    descuento: 20,
    categoriaId: 2,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.04.00 AM.jpeg",
    vendedor: "NaturaGlow",
    vendedorId: 5,
    calificacion: 4.9,
    resenas: 203,
    stock: 25,
    etiquetas: ["facial", "sérum", "vitamina c", "antioxidante", "manchas"],
    destacado: true,
    nuevo: false,
  },
  {
    id: 6,
    nombre: "Crema Hidratante con Ácido Hialurónico",
    descripcion: "Crema de día y noche con ácido hialurónico de triple peso molecular. Hidratación profunda por 72 horas. Sin fragancia, apta para piel sensible.",
    precio: 75000,
    descuento: 0,
    categoriaId: 2,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.04.00 AM (1).jpeg",
    vendedor: "NaturaGlow",
    vendedorId: 5,
    calificacion: 4.7,
    resenas: 156,
    stock: 40,
    etiquetas: ["facial", "crema", "hialurónico", "hidratante", "sensible"],
    destacado: true,
    nuevo: false,
  },
  {
    id: 7,
    nombre: "Mascarilla de Arcilla Verde",
    descripcion: "Mascarilla purificante con arcilla verde y extracto de árbol de té. Limpia los poros en profundidad y controla el exceso de sebo.",
    precio: 38000,
    descuento: 5,
    categoriaId: 2,
    imagen: "assets/images/WhatsApp Image 2026-06-25 at 11.04.00 AM (2).jpeg",
    vendedor: "BellezaNatural",
    vendedorId: 4,
    calificacion: 4.4,
    resenas: 88,
    stock: 60,
    etiquetas: ["facial", "mascarilla", "arcilla", "poros", "purificante"],
    destacado: false,
    nuevo: true,
  },
];

export const usuarios = [
  {
    id: 1,
    nombre: "Admin",
    apellido: "BeautyShop",
    email: "admin@beautyshop.com",
    rol: "admin",
    avatar: "assets/images/avatar-admin.jpg",
    telefono: "3001234567",
    direccion: "Calle 100 #15-20",
    ciudad: "Bogotá",
    fechaRegistro: "2026-01-01T00:00:00Z",
    activo: true,
  }
];

export const resenas = [
  {
    id: 1,
    productoId: 5,
    usuarioId: 2,
    usuarioNombre: "María L.",
    calificacion: 5,
    comentario: "¡Increíble sérum!",
    fecha: "2026-05-10T12:00:00Z",
  }
];

export const ordenes = [
  {
    id: "ORD-001",
    usuarioId: 2,
    subtotal: 209000,
    total: 179000,
    estado: "entregado",
    fechaOrden: "2026-05-20T10:00:00Z",
  },
];
